import type { ErrorCorrectionLevel } from "./qr";
export type PayloadKind="url"|"text"|"whatsapp"|"wifi"; export type ModuleStyle="square"|"rounded"|"dot"; export type EyeStyle="square"|"rounded"|"dot";
export interface QrProject{schemaVersion:1;name:string;payloadKind:PayloadKind;value:string;secondaryValue:string;wifiSecurity:"WPA"|"WEP"|"nopass";wifiHidden:boolean;tracking:{enabled:boolean;id:string;campaign:string;variant:string};errorCorrection:ErrorCorrectionLevel;size:number;margin:number;foreground:string;background:string;moduleStyle:ModuleStyle;moduleScale:number;eyeStyle:EyeStyle;eyeScale:number;backgroundImage:string|null;backgroundImageOpacity:number;surfaceOpacity:number;logoImage:string|null;logoScale:number;logoPadding:number;logoRadius:number;removeLogoBackground:boolean;removalThreshold:number;updatedAt:string}
export function createTrackingId(){const d=new Date().toISOString().slice(0,10).replaceAll("-","");const r=crypto.randomUUID().replaceAll("-","").slice(0,8).toUpperCase();return`QR-${d}-${r}`}
export const DEFAULT_PROJECT:QrProject={schemaVersion:1,name:"QR Carro Chefe",payloadKind:"url",value:"https://carrochefe.com",secondaryValue:"",wifiSecurity:"WPA",wifiHidden:false,tracking:{enabled:false,id:"",campaign:"",variant:""},errorCorrection:"H",size:1200,margin:4,foreground:"#0B0907",background:"#F3DFC0",moduleStyle:"dot",moduleScale:.72,eyeStyle:"rounded",eyeScale:.94,backgroundImage:null,backgroundImageOpacity:.24,surfaceOpacity:.94,logoImage:null,logoScale:.18,logoPadding:.9,logoRadius:.8,removeLogoBackground:false,removalThreshold:48,updatedAt:new Date().toISOString()};
function escapeWifi(v:string){return v.replace(/([\\;,:"])/g,"\\$1")} export function isTrackable(p:QrProject){return p.payloadKind==="url"} function normalizeUrl(raw:string){const v=raw.trim();if(!v)throw new Error("Informe uma URL para gerar o QR Code.");return new URL(/^[a-z][a-z\d+.-]*:\/\//i.test(v)?v:`https://${v}`)}
export function buildPayload(p:QrProject){if(p.payloadKind==="url"){const u=normalizeUrl(p.value);if(p.tracking.enabled){if(!p.tracking.id.trim())throw new Error("Gere ou informe um ID de rastreamento.");u.searchParams.set("cc_qr",p.tracking.id.trim());if(p.tracking.campaign.trim())u.searchParams.set("cc_campaign",p.tracking.campaign.trim());else u.searchParams.delete("cc_campaign");if(p.tracking.variant.trim())u.searchParams.set("cc_variant",p.tracking.variant.trim());else u.searchParams.delete("cc_variant")}return u.toString()}if(p.payloadKind==="text"){if(!p.value.trim())throw new Error("Digite o texto que será armazenado no QR Code.");return p.value}if(p.payloadKind==="whatsapp"){const phone=p.value.replace(/\D/g,"");if(!phone)throw new Error("Informe o telefone do WhatsApp com DDD e código do país.");const u=new URL(`https://wa.me/${phone}`);if(p.secondaryValue.trim())u.searchParams.set("text",p.secondaryValue.trim());return u.toString()}const ssid=p.value.trim();if(!ssid)throw new Error("Informe o nome da rede Wi-Fi.");return`WIFI:T:${p.wifiSecurity};S:${escapeWifi(ssid)};P:${escapeWifi(p.secondaryValue)};H:${p.wifiHidden?"true":"false"};;`}
export function cloneDefaultProject():QrProject{return JSON.parse(JSON.stringify(DEFAULT_PROJECT)) as QrProject} export function sanitizeProject(value:unknown):QrProject{if(!value||typeof value!=="object")throw new Error("Arquivo de projeto inválido.");const c=value as Partial<QrProject>;if(c.schemaVersion!==1)throw new Error("Versão de projeto não suportada.");const n={...cloneDefaultProject(),...c} as QrProject;n.tracking={...DEFAULT_PROJECT.tracking,...(c.tracking??{})};n.updatedAt=new Date().toISOString();return n}
export function buildManifest(p:QrProject,payload:string){return{schema:"carro-chefe.qr-manifest/v1",generatedAt:new Date().toISOString(),projectName:p.name,tracking:p.tracking.enabled&&isTrackable(p)?{id:p.tracking.id,campaign:p.tracking.campaign||null,variant:p.tracking.variant||null,queryParams:{id:"cc_qr",campaign:"cc_campaign",variant:"cc_variant"}}:null,payload,design:{foreground:p.foreground,background:p.background,moduleStyle:p.moduleStyle,eyeStyle:p.eyeStyle,errorCorrection:p.errorCorrection,hasBackgroundImage:Boolean(p.backgroundImage),hasLogoImage:Boolean(p.logoImage)}}}
