import { generateQrMatrix } from "./qr"; import type { QrProject } from "./project";
export interface RenderResult{version:number;modules:number;byteLength:number}
const loadImage=(src:string)=>new Promise<HTMLImageElement>((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=()=>reject(new Error("Não foi possível carregar a imagem selecionada."));i.src=src});
function rr(c:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,r:number){r=Math.max(0,Math.min(r,w/2,h/2));c.beginPath();c.moveTo(x+r,y);c.lineTo(x+w-r,y);c.quadraticCurveTo(x+w,y,x+w,y+r);c.lineTo(x+w,y+h-r);c.quadraticCurveTo(x+w,y+h,x+w-r,y+h);c.lineTo(x+r,y+h);c.quadraticCurveTo(x,y+h,x,y+h-r);c.lineTo(x,y+r);c.quadraticCurveTo(x,y,x+r,y);c.closePath()}
function cover(c:CanvasRenderingContext2D,i:HTMLImageElement,s:number){const k=Math.max(s/i.width,s/i.height),w=i.width*k,h=i.height*k;c.drawImage(i,(s-w)/2,(s-h)/2,w,h)}
const finder=(r:number,col:number,n:number)=>(r<7&&col<7)||(r<7&&col>=n-7)||(r>=n-7&&col<7);
function moduleShape(c:CanvasRenderingContext2D,x:number,y:number,cell:number,p:QrProject){const sc=p.moduleStyle==="square"?1:p.moduleScale,s=cell*sc,o=(cell-s)/2;if(p.moduleStyle==="dot"){c.beginPath();c.arc(x+cell/2,y+cell/2,s/2,0,Math.PI*2);c.fill()}else if(p.moduleStyle==="rounded"){rr(c,x+o,y+o,s,s,s*.28);c.fill()}else c.fillRect(x,y,cell,cell)}
function eye(c:CanvasRenderingContext2D,x:number,y:number,cell:number,p:QrProject){const full=cell*7,s=full*p.eyeScale,o=(full-s)/2,ox=x+o,oy=y+o,ring=s/7,inner=s-ring*4;c.fillStyle=p.foreground;if(p.eyeStyle==="dot"){c.beginPath();c.arc(ox+s/2,oy+s/2,s/2,0,Math.PI*2);c.fill();c.fillStyle=p.background;c.beginPath();c.arc(ox+s/2,oy+s/2,s/2-ring,0,Math.PI*2);c.fill();c.fillStyle=p.foreground;c.beginPath();c.arc(ox+s/2,oy+s/2,inner/2,0,Math.PI*2);c.fill();return}const radius=p.eyeStyle==="rounded"?ring*1.5:0;rr(c,ox,oy,s,s,radius);c.fill();c.fillStyle=p.background;rr(c,ox+ring,oy+ring,s-ring*2,s-ring*2,radius*.72);c.fill();c.fillStyle=p.foreground;rr(c,ox+ring*2,oy+ring*2,inner,inner,radius*.5);c.fill()}
function removeBg(i:HTMLImageElement,t:number){const k=Math.min(1,1000/Math.max(i.width,i.height)),cv=document.createElement("canvas");cv.width=Math.max(1,Math.round(i.width*k));cv.height=Math.max(1,Math.round(i.height*k));const c=cv.getContext("2d",{willReadFrequently:true});if(!c)return cv;c.drawImage(i,0,0,cv.width,cv.height);const d=c.getImageData(0,0,cv.width,cv.height),pts=[[1,1],[cv.width-2,1],[1,cv.height-2],[cv.width-2,cv.height-2]],a=[0,0,0];for(const[x,y]of pts){const n=(Math.max(0,y)*cv.width+Math.max(0,x))*4;a[0]+=d.data[n];a[1]+=d.data[n+1];a[2]+=d.data[n+2]}a[0]/=4;a[1]/=4;a[2]/=4;for(let n=0;n<d.data.length;n+=4){const dr=d.data[n]-a[0],dg=d.data[n+1]-a[1],db=d.data[n+2]-a[2],dist=Math.sqrt(dr*dr+dg*dg+db*db);if(dist<=t)d.data[n+3]=0;else if(dist<t+28)d.data[n+3]=Math.round(255*((dist-t)/28))}c.putImageData(d,0,0);return cv}
export async function renderQr(canvas:HTMLCanvasElement,p:QrProject,payload:string):Promise<RenderResult>{const qr=generateQrMatrix(payload,p.errorCorrection),n=qr.modules.length,size=Math.round(p.size);canvas.width=size;canvas.height=size;const c=canvas.getContext("2d");if(!c)throw new Error("Canvas indisponível neste navegador.");c.clearRect(0,0,size,size);c.fillStyle=p.background;c.fillRect(0,0,size,size);const[bg,logo]=await Promise.all([p.backgroundImage?loadImage(p.backgroundImage):Promise.resolve(null),p.logoImage?loadImage(p.logoImage):Promise.resolve(null)]);if(bg){c.save();c.globalAlpha=p.backgroundImageOpacity;cover(c,bg,size);c.restore()}const total=n+p.margin*2,cell=Math.max(1,Math.floor(size/total)),px=total*cell,origin=Math.floor((size-px)/2);c.save();c.globalAlpha=p.surfaceOpacity;c.fillStyle=p.background;c.fillRect(origin,origin,px,px);c.restore();let lb:{x:number;y:number;width:number;height:number;padding:number}|null=null;if(logo){const max=n*cell*p.logoScale,ratio=logo.width/logo.height,w=ratio>=1?max:max*ratio,h=ratio>=1?max/ratio:max,pad=cell*p.logoPadding;lb={x:size/2-w/2,y:size/2-h/2,width:w,height:h,padding:pad}}const intersects=(r:number,col:number)=>{if(!lb)return false;const x=origin+(p.margin+col)*cell+cell/2,y=origin+(p.margin+r)*cell+cell/2;return x>=lb.x-lb.padding&&x<=lb.x+lb.width+lb.padding&&y>=lb.y-lb.padding&&y<=lb.y+lb.height+lb.padding};c.fillStyle=p.foreground;for(let r=0;r<n;r++)for(let col=0;col<n;col++){if(!qr.modules[r][col]||finder(r,col,n)||intersects(r,col))continue;moduleShape(c,origin+(p.margin+col)*cell,origin+(p.margin+r)*cell,cell,p)}for(const[r,col]of[[0,0],[0,n-7],[n-7,0]])eye(c,origin+(p.margin+col)*cell,origin+(p.margin+r)*cell,cell,p);if(logo&&lb){c.fillStyle=p.background;rr(c,lb.x-lb.padding,lb.y-lb.padding,lb.width+lb.padding*2,lb.height+lb.padding*2,cell*p.logoRadius);c.fill();c.drawImage(p.removeLogoBackground?removeBg(logo,p.removalThreshold):logo,lb.x,lb.y,lb.width,lb.height)}return{version:qr.version,modules:n,byteLength:qr.byteLength}}
